trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'PublishTemplates'
  displayName: 'PublishTemplates'
  jobs: 
    - job: 'PublishTemplates'
      steps:
      - task: CopyFiles@2
        displayName: 'Copy composing to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: infra-templates
          TargetFolder: '$(build.artifactstagingdirectory)/templates'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
- stage: 'Test'
  jobs:
  - deployment: 'DeployToTest'
    environment: 'infrastructure-test'
    strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.DefaultWorkingDirectory)'
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: '<subscription-connection-name>'
                subscriptionId: '<subscriptiont-id>'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'erwin-test'
                location: 'West Europe'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.DefaultWorkingDirectory)/drop/templates/api.json'
                csmParametersFile: '$(System.DefaultWorkingDirectory)/drop/templates/api.test.json'
                deploymentMode: 'Incremental'
